### ISSUE TITLE
Improvement - Let's encrypt for certificate generation

### ISSUE THREAD

**Issue by fwsl** [jcrodriguez-dis/vpl-xmlrpc-jail#15]
Hi

It would be nice to have a valid certificate instead of self-signed one. 
Certificates can be obtained using i.a. certbot. Example https://certbot.eff.org/all-instructions/#debian-8-jessie-none-of-the-above

https://certbot.eff.org/
https://letsencrypt.org

**Comment by jcrodriguez-dis** [comment]
Hi
Yes, I know that It would be better to have a valid certificate instead of a self-signed. To get this using any free certificate service you must know that the certificate and key (in PEM format) must be placed at
/etc/vpl/cert.pem
/etc/vpl/key.pem
these files must have no other allow than read only access for root .
Restart the service to read the new values if they change.

Best regards,
Juan Carlos.

**Comment by fwsl** [comment]
Yes, I know that. But instead of generating self-signed certificate, jail server could automatically obtain valid certificate from letsencrypt.org. There would be no need for manual certificate management.

Best regards
Grzegorz

**Comment by jderriks** [comment]
Installing certbot and then using cron to let certbot update those files in /etc/vpl should not be so hard. Is it possible to specify those locations to certbot?

**Comment by jcrodriguez-dis** [comment]
After studying how the process of activation and update of the certificates works for certbot. Yes, it's seem not too hard to add certbot support. This feature is added to the TODO list.

**Comment by jcrodriguez-dis** [comment]
Resolved in v2.6.0
