### ISSUE TITLE
Jail server on Ubuntu 18.04: Jail error: jail /etc/passwd with insecure permissions (must be 0x00)

### ISSUE THREAD

**Issue by torinfo** [jcrodriguez-dis/vpl-xmlrpc-jail#28]
I cannot start a freshly installed jail server on ubunt 18.04 LTS

Whatever permissions I give /etc/passwd, it doesn't start. What are the correct permissions? I tried 0600, 0000 and 0400.

Thank you!

**Comment by torinfo** [comment]
Found it in the source.  The message complains about /etc/passwd, but it's actually checking /etc/shadow.

Line 83 of vpl-jail-server.h

**Comment by jcrodriguez-dis** [comment]
Hello torinfo,
the startup script of the service create fake $JAIL/etc/passwd and $JAIL/etc/group files and modify $JAIL/ETC/shadow if exists with the apropiate permissions. $JAIl is the directory fo the replicate root file system. The service daemon check the  permissions of this files. If this checks fail then the problem is at the startup script that fail setting the correct permissions.

Thanks for the bug report. The message text will be corrected in the next release.

Best regards
Juan Carlos.

**Comment by jcrodriguez-dis** [comment]
Please try the new 2.5 version
