### ISSUE TITLE
Remove SSLv3 support for VPL server

### ISSUE THREAD

**Issue by hc6pe** [jcrodriguez-dis/vpl-xmlrpc-jail#8]
hi, when installed, this server accepts SSLv3 in https as shown:
sudo nmap --script ssl-enum-ciphers vpl.xxx.aaa

Starting Nmap 7.12 ( https://nmap.org ) at 2016-07-22 08:24 ECT
Nmap scan report for vpl.xxx.aaa (1.2.3.4)
Host is up (0.041s latency).
Not shown: 998 filtered ports
PORT    STATE SERVICE
80/tcp  open  http
443/tcp open  https
| ssl-enum-ciphers: 
|   SSLv3: 
|     ciphers: 
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors: 
| 
|     cipher preference: indeterminate
|     cipher preference error: Too few ciphers supported
|     warnings: 
|       CBC-mode cipher in SSLv3 (CVE-2014-3566)
|   TLSv1.0: 
|     ciphers: 
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors: 
| 
|     cipher preference: indeterminate
|     cipher preference error: Too few ciphers supported
|   TLSv1.1: 
|     ciphers: 
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors: 
| 
|     cipher preference: indeterminate
|     cipher preference error: Too few ciphers supported
|_  least strength: C

Nmap done: 1 IP address (1 host up) scanned in 12.37 seconds

Also please evaluate the possibility to configure the installer to listen, by default on the interface 127.0.0.1 this way VPL will not be exposed to the internet.

**Comment by jcrodriguez-dis** [comment]
Hello hc6pe,
thank for your bug report. First I must say that the use of a strong cipher in the jail connexions is not a critical issue. We don't send password or other important data to the jail server, but the students' source files. We think that removing the https protocol due to the presence of security bugs in the protocol is worst than the problem, because it lead to the use of a protocol with no cipher. VPL uses openssl, the new versions of this cipher library removes the use of SSLv3 without modifying VPL. But due to your bug report, we have released a new jail-server version (2.2.1) that remove the use of SSLv3 explicity.

Best regards.

**Comment by jcrodriguez-dis** [comment]
Please, check if it's OK for you the new 2.2.1 version.

**Comment by hc6pe** [comment]
thanks.. I have installed 2.2.1 in a clean server and it has SSLv3 removed.

openssl s_client -connect 127.0.0.1:4430 -ssl3
CONNECTED(00000003)
140351327438752:error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure:s3_pkt.c:1259:SSL alert number 40
140351327438752:error:1409E0E5:SSL routines:SSL3_WRITE_BYTES:ssl handshake failure:s3_pkt.c:598:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : SSLv3
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1469727638
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
